FROM continuumio/miniconda3:latest
LABEL software="CuteSV"
LABEL version="2.0.2"
LABEL github_repo="https://github.com/tjiangHIT/cuteSV"

SHELL ["/bin/bash", "--login", "-c"]

RUN pip install cutesv==2.0.2
